apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: firefly-iii-application-system
  namespace: webgrip
  title: firefly-iii-application System
  description: |
    Placeholder description
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: webgrip/firefly-iii-application
    backstage.io/adr-location: docs/adrs
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: n8n
  tags:
    - firefly-iii-application
  links:
    - url: https://firefly-iii-application.webgrip.test/
      title: Development URL
      icon: dashboard
      type: website
    - url: https://firefly-iii-application.staging.k8s.webgrip.nl/
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/firefly-iii-application
      title: Source Code
      icon: github
      type: source
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/operations-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: firefly-iii-application
  namespace: webgrip
  title: application
  description: |
    Placeholder description
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: webgrip/firefly-iii-application
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: n8n
  tags:
    - application
    - nodejs
    - automation
  links:
    - url: https://firefly-iii-application.webgrip.test/
      title: Development URL
      icon: dashboard
      type: website
    - url: https://firefly-iii-application.staging.k8s.webgrip.nl/
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/firefly-iii-application
      title: Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: firefly-iii-application-system
