namespace: firefly-iii-application

_shared_config:
  hostname: &hostname firefly-iii-application.staging.k8s.webgrip.nl
  url: &url https://firefly-iii-application.staging.k8s.webgrip.nl

# Official Firefly III chart configuration
firefly-iii:
  enabled: true

  # Use our custom image
  image:
    registry: "docker.io"
    repository: "webgrip/firefly-iii-application"
    tag: "latest"
    pullPolicy: Always

  # Security context
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1500
    fsGroupChangePolicy: OnRootMismatch

  securityContext:
    runAsUser: 1500
    runAsGroup: 1500
    allowPrivilegeEscalation: false

  # Resource limits
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  # Persistent storage for uploads
  persistence:
    enabled: true
    size: 10Gi
    retain: true

  # Application configuration using existing secrets
  config:
    existingSecret: firefly-iii-application-secrets

    # Non-secret environment variables
    env:
      # App configuration
      APP_NAME: firefly-iii-application
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: *url
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_TIMEZONE: Europe/Amsterdam

      # Database configuration
      DB_STRICT: "false"
      DB_CONNECTION: mysql
      DB_HOST: firefly-iii-application-mariadb
      DB_PORT: "3306"
      DB_DATABASE: firefly-iii-application
      DB_USERNAME: firefly-iii-application

      # Security
      REQUIRE_HTTPS: "true"
      TRUSTED_PROXIES: "**"

      # Logging
      LOG_CHANNEL: stderr
      LOG_LEVEL: info

      # Redis configuration
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: phpredis
      REDIS_PREFIX: firefly-iii-application_
      REDIS_HOST: firefly-iii-application-redis-master
      REDIS_PORT: "6379"

      # Additional Firefly III configuration
      IS_DOCKER: "true"
      FILESYSTEM_DRIVER: local
      EXPANDED_LOGGING: "true"
      PDF_GENERATOR: snappdf

    # Secret environment variables from existing secret
    envValueFrom:
      APP_KEY:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: app-key
      DB_PASSWORD:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: mariadb-password
      REDIS_PASSWORD:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: redis-password
      API_SECRET:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: api-secret
      UPDATE_SECRET:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: update-secret
      WEBCRON_SECRET:
        secretKeyRef:
          name: firefly-iii-application-secrets
          key: webcron-secret

  # Service configuration
  service:
    type: ClusterIP
    port: 80

  # Ingress configuration for Traefik
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: ingress-traefik-ryan-home-ip-allow-list@kubernetescrd
    hosts:
      - host: *hostname
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: letsencrypt-firefly-iii-application
        hosts:
          - *hostname

  # Health checks
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 30

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10

  startupProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 30

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: firefly-iii-application-secrets
    existingSecretPasswordKey: redis-password
  primary:
    persistence:
      enabled: true
      size: 2Gi
  replica:
    replicaCount: 0

# MariaDB configuration
mariadb:
  enabled: true
  auth:
    rootPassword: ""
    database: firefly-iii-application
    username: firefly-iii-application
    existingSecret: firefly-iii-application-secrets
    existingSecretPasswordKey: mariadb-password
    existingSecretRootPasswordKey: mariadb-root-password
  primary:
    persistence:
      enabled: true
      size: 5Gi
