apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Application secrets
  app-key: {{ index .Values "app-key" | b64enc | quote }}
  api-secret: {{ index .Values "api-secret" | b64enc | quote }}
  
  # Database secrets
  mariadb-password: {{ index .Values "mariadb-password" | b64enc | quote }}
  mariadb-root-password: {{ index .Values "mariadb-root-password" | b64enc | quote }}
  
  # Redis secrets
  redis-password: {{ index .Values "redis-password" | b64enc | quote }}